fileGroups:
  storybookConfig:
    - ".storybook/**/*"

tasks:
  storybook:
    command: yarn storybook dev --port=6006
    preset: watcher
  storybook-build:
    command: yarn storybook build --output-dir=storybook-static
    inputs:
      - "@group(storybookConfig)"
    outputs:
      - "storybook-static/"
  chromatic:
    command: yarn chromatic --storybook-build-dir=storybook-static --exit-zero-on-changes
    inputs:
      - "*.*"
      - "$CHROMATIC_PROJECT_TOKEN"
    deps:
      - storybook-build
